# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install Dependencies
      run: npm install
    
    - name: Build
      run: npm run build
    
    - name: Deploy
      run: |
        git config --global user.name haramrit09k
        git config --global user.email haramrit09k@gmail.com
        git remote set-url origin https://${{secrets.ACCESS_TOKEN}}@github.com/haramrit09k/haramrit09k.github.io.git
        npm run deploy
    
#     - run: npm ci
#     - run: npm publish
#       if: github.event == 'push'


