name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for gh-pages to push to branch

    strategy:
      matrix:
        node-version: [18.x]  # Use LTS version

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install Dependencies
      run: npm install
    
    - name: Build
      run: npm run build
    
    - name: Deploy
      run: npm run deploy
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub